//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public string SystemUserName { get; set; }
        public string SystemUserPassword { get; set; }
        public string SystemUserRole { get; set; }

        public SystemUser() { }

        public SystemUser(string SystemUserName, string SystemUserPassword, string SystemUserRole) {
            this.SystemUserName = SystemUserName;
            this.SystemUserPassword = SystemUserPassword;
            this.SystemUserRole = SystemUserRole;
        }
    }
}
