//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishPhoto
    {
        public int PhotoCode { get; set; }
        public string PhotoPath { get; set; }
        public int DishCode { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
